"""Restore plan generator — creates PDF disaster recovery runbook."""

import json
import logging
import socket
from datetime import UTC, datetime
from pathlib import Path

import aiosqlite
from jinja2 import Environment, select_autoescape

from app.core.config import ArkiveConfig
from app.core.security import decrypt_config
from app.services.repo_paths import build_repo_path

logger = logging.getLogger("arkive.restore_plan")

RESTORE_PLAN_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body { font-family: 'Inter', 'Segoe UI', sans-serif; margin: 40px; color: #1c2333; line-height: 1.6; }
h1 { color: #0d1117; border-bottom: 3px solid #388bfd; padding-bottom: 10px; }
h2 { color: #388bfd; margin-top: 30px; }
h3 { color: #1c2333; }
table { width: 100%; border-collapse: collapse; margin: 15px 0; }
th { background: #1c2333; color: white; padding: 10px; text-align: left; }
td { padding: 8px 10px; border-bottom: 1px solid #e1e4e8; }
tr:nth-child(even) { background: #f6f8fa; }
.warning { background: #fff3cd; border-left: 4px solid #ffc107; padding: 12px; margin: 15px 0; }
.critical { background: #f8d7da; border-left: 4px solid #e94560; padding: 12px; margin: 15px 0; }
.info { background: #d1ecf1; border-left: 4px solid #388bfd; padding: 12px; margin: 15px 0; }
code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-family: 'JetBrains Mono', monospace; }
pre { background: #0d1117; color: #e6edf3; padding: 16px; border-radius: 6px; overflow-x: auto; }
.footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e1e4e8; color: #666; font-size: 12px; }
</style>
</head>
<body>
<h1>🛡️ Arkive Disaster Recovery Plan</h1>
<p><strong>Server:</strong> {{ hostname }}<br>
<strong>Generated:</strong> {{ generated_at }}<br>
<strong>Platform:</strong> {{ platform }}</p>

<div class="critical">
<strong>⚠️ CRITICAL:</strong> Store this document securely. It contains the information needed
to restore your entire server from scratch.
</div>

<h2>1. Restic Repository Access</h2>
<div class="warning">
<strong>Encryption Password:</strong> Your restic repository is encrypted. You MUST have the
encryption password to restore any data. If you lose this password, your backups are
permanently inaccessible.
</div>

<h2>2. Storage Targets</h2>
<table>
<tr><th>Name</th><th>Type</th><th>Snapshots</th><th>Size</th></tr>
{% for target in targets %}
<tr>
<td>{{ target.name }}</td>
<td>{{ target.type }}</td>
<td>{{ target.snapshot_count }}</td>
<td>{{ target.total_size_display }}</td>
</tr>
{% endfor %}
</table>

<h2>3. Backed Up Databases</h2>
<table>
<tr><th>Container</th><th>Type</th><th>Database</th><th>Restore Command</th></tr>
{% for db in databases %}
<tr>
<td>{{ db.container_name }}</td>
<td>{{ db.db_type }}</td>
<td>{{ db.db_name }}</td>
<td><code>{{ db.restore_cmd }}</code></td>
</tr>
{% endfor %}
</table>

<h2>4. Restore Procedure</h2>
<h3>Step 1: Install Arkive on new server</h3>
<pre>docker run -d \\
  --name arkive \\
  -v /mnt/user/appdata/arkive:/config \\
  -v /var/run/docker.sock:/var/run/docker.sock:ro \\
  -p 8200:8200 \\
  ghcr.io/islamdiaa/arkive:latest</pre>

<h3>Step 2: Configure storage target</h3>
<p>Add the same storage target(s) used for backups via the Arkive UI.</p>

<h3>Step 3: List available snapshots</h3>
<pre>docker exec arkive restic -r \
{{ targets[0].repo_path if targets else 'rclone:TARGET:arkive-backups' }} snapshots</pre>

<h3>Step 4: Restore database dumps</h3>
<pre>docker exec arkive restic -r \
{{ targets[0].repo_path if targets else 'rclone:TARGET:arkive-backups' }} \
restore SNAPSHOT_ID --target /config/restore/</pre>

<h3>Step 5: Restore each database</h3>
{% for db in databases %}
<p><strong>{{ db.container_name }} ({{ db.db_type }}):</strong></p>
<pre>{{ db.full_restore_cmd }}</pre>
{% endfor %}

{% if flash_available %}
<h3>Step 6: Restore Flash Config (Unraid)</h3>
<pre>tar -xzf /config/restore/config/dumps/flash_TIMESTAMP.tar.gz -C /boot/config/</pre>
{% endif %}

<h2>5. Container Inventory</h2>
<table>
<tr><th>Container</th><th>Image</th><th>Status</th><th>Priority</th></tr>
{% for container in containers %}
<tr>
<td>{{ container.name }}</td>
<td>{{ container.image }}</td>
<td>{{ container.status }}</td>
<td>{{ container.priority }}</td>
</tr>
{% endfor %}
</table>

<h2>6. Watched Directories</h2>
<table>
<tr><th>Path</th><th>Label</th></tr>
{% for dir in directories %}
<tr><td>{{ dir.path }}</td><td>{{ dir.label }}</td></tr>
{% endfor %}
</table>

<div class="footer">
Generated by Arkive v{{ version }} | {{ generated_at }}
</div>
</body>
</html>
"""


class RestorePlanGenerator:
    """Generates restore plan PDF."""

    def __init__(self, config: ArkiveConfig):
        self.config = config

    async def generate(self) -> str:
        """Generate restore plan HTML and convert to PDF. Returns PDF path."""
        from app import __version__

        async with aiosqlite.connect(self.config.db_path) as db:
            db.row_factory = aiosqlite.Row

            # Targets
            cursor = await db.execute("SELECT * FROM storage_targets WHERE enabled = 1")
            targets_raw = await cursor.fetchall()
            targets = []
            for t in targets_raw:
                t = dict(t)
                size = t.get("total_size_bytes", 0)
                t["total_size_display"] = self._format_bytes(size)
                t["config"] = decrypt_config(t.get("config", "{}"), str(self.config.config_dir))
                t["repo_path"] = self._repo_path(t)
                targets.append(t)

            # Containers
            cursor = await db.execute("SELECT * FROM discovered_containers ORDER BY priority")
            containers = [dict(c) for c in await cursor.fetchall()]

            # Directories
            cursor = await db.execute("SELECT * FROM watched_directories WHERE enabled = 1")
            directories = [dict(d) for d in await cursor.fetchall()]

            # Platform
            cursor = await db.execute("SELECT value FROM settings WHERE key = 'platform'")
            platform_row = await cursor.fetchone()
            platform = platform_row["value"] if platform_row else "linux"

        # Build database restore commands
        databases = []
        for c in containers:
            dbs = (
                json.loads(c.get("databases", "[]")) if isinstance(c.get("databases"), str) else c.get("databases", [])
            )
            for d in dbs:
                if isinstance(d, dict):
                    db_type = d.get("db_type", "")
                    db_name = d.get("db_name", "")
                    container_name = d.get("container_name", c.get("name", ""))
                    restore_cmd, full_cmd = self._get_restore_commands(db_type, db_name, container_name)
                    databases.append(
                        {
                            "container_name": container_name,
                            "db_type": db_type,
                            "db_name": db_name,
                            "restore_cmd": restore_cmd,
                            "full_restore_cmd": full_cmd,
                        }
                    )

        env = Environment(autoescape=select_autoescape(["html"]))
        template = env.from_string(RESTORE_PLAN_TEMPLATE)
        html = template.render(
            hostname=socket.gethostname(),
            generated_at=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
            platform=platform,
            version=__version__,
            targets=targets,
            databases=databases,
            containers=containers,
            directories=directories,
            flash_available=platform == "unraid",
        )

        # Write HTML
        html_path = str(self.config.config_dir / "restore-plan.html")
        Path(html_path).write_text(html)

        # Convert to PDF
        pdf_path = str(self.config.config_dir / "restore-plan.pdf")
        try:
            from weasyprint import HTML

            HTML(string=html).write_pdf(pdf_path)
        except Exception as e:
            logger.warning("PDF generation failed (WeasyPrint): %s — falling back to HTML", e)
            pdf_path = html_path

        return pdf_path

    def _repo_path(self, target: dict) -> str:
        """Return the operator-facing restic repository path for a target."""
        return build_repo_path(target)

    def _get_restore_commands(self, db_type: str, db_name: str, container: str) -> tuple[str, str]:
        """Get restore commands for a database type."""
        if db_type == "postgres":
            short = "psql -U postgres < dump.sql"
            full = f"gunzip -c {container}_{db_name}_*.sql.gz | docker exec -i {container} psql -U postgres"
            return short, full
        elif db_type == "sqlite":
            short = f"sqlite3 /path/to/{db_name} '.restore backup.sqlite3'"
            full = f"cp {container}_{db_name}_*.sqlite3 /mnt/user/appdata/{container}/data/{db_name}"
            return short, full
        elif db_type in ("mariadb", "mysql"):
            short = "mysql -u root < dump.sql"
            full = f"gunzip -c {container}_{db_name}_*.sql.gz | docker exec -i {container} mysql -u root"
            return short, full
        elif db_type == "mongodb":
            short = "mongorestore --archive < dump.archive"
            full = f"gunzip -c {container}_{db_name}_*.archive.gz | docker exec -i {container} mongorestore --archive"
            return short, full
        elif db_type == "redis":
            short = "cp dump.rdb /data/dump.rdb && redis-cli SHUTDOWN NOSAVE"
            full = f"cp {container}_redis_*.rdb /mnt/user/appdata/{container}/data/dump.rdb"
            return short, full
        return "See documentation", "See documentation"

    def _format_bytes(self, size: int) -> str:
        for unit in ["B", "KB", "MB", "GB", "TB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} PB"
